# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layouts/base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutGraphStatus = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraphStatus.setObjectName("verticalLayoutGraphStatus")
        self.verticalLayoutGraph = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraph.setObjectName("verticalLayoutGraph")
        self.label_replace = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_replace.sizePolicy().hasHeightForWidth())
        self.label_replace.setSizePolicy(sizePolicy)
        self.label_replace.setObjectName("label_replace")
        self.verticalLayoutGraph.addWidget(self.label_replace)
        self.verticalLayoutGraphStatus.addLayout(self.verticalLayoutGraph)
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayoutGraphStatus.addWidget(self.lbl_status)
        self.horizontalLayout.addLayout(self.verticalLayoutGraphStatus)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuConfiguracoes = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracoes.setObjectName("menuConfiguracoes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayoutOptions = QtWidgets.QVBoxLayout()
        self.verticalLayoutOptions.setObjectName("verticalLayoutOptions")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_3.setProperty("value", 40)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_4.addWidget(self.horizontalSlider_3)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setMaximum(50)
        self.horizontalSlider.setProperty("value", 5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_4.addWidget(self.horizontalSlider)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_2.setProperty("value", 20)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_4.addWidget(self.horizontalSlider_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutBtns = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBtns.setObjectName("horizontalLayoutBtns")
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBtns.addItem(spacerItem1)
        self.verticalLayoutBtns = QtWidgets.QVBoxLayout()
        self.verticalLayoutBtns.setObjectName("verticalLayoutBtns")
        self.btn_calib = QtWidgets.QPushButton(self.tab_2)
        self.btn_calib.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_calib.setObjectName("btn_calib")
        self.verticalLayoutBtns.addWidget(self.btn_calib)
        self.horizontalLayoutBtns.addLayout(self.verticalLayoutBtns)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBtns.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayoutBtns)
        self.horizontalLayoutThreshould = QtWidgets.QHBoxLayout()
        self.horizontalLayoutThreshould.setObjectName("horizontalLayoutThreshould")
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutThreshould.addItem(spacerItem3)
        self.sl_threshould = QtWidgets.QSlider(self.tab_2)
        self.sl_threshould.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sl_threshould.sizePolicy().hasHeightForWidth())
        self.sl_threshould.setSizePolicy(sizePolicy)
        self.sl_threshould.setOrientation(QtCore.Qt.Vertical)
        self.sl_threshould.setObjectName("sl_threshould")
        self.horizontalLayoutThreshould.addWidget(self.sl_threshould)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutThreshould.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayoutThreshould)
        self.verticalLayoutCheckBoxes = QtWidgets.QVBoxLayout()
        self.verticalLayoutCheckBoxes.setObjectName("verticalLayoutCheckBoxes")
        self.cb_emg = QtWidgets.QCheckBox(self.tab_2)
        self.cb_emg.setObjectName("cb_emg")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_emg)
        self.cb_hbt = QtWidgets.QCheckBox(self.tab_2)
        self.cb_hbt.setObjectName("cb_hbt")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_hbt)
        self.cb_ret = QtWidgets.QCheckBox(self.tab_2)
        self.cb_ret.setObjectName("cb_ret")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_ret)
        self.cb_env = QtWidgets.QCheckBox(self.tab_2)
        self.cb_env.setObjectName("cb_env")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_env)
        self.cb_lim = QtWidgets.QCheckBox(self.tab_2)
        self.cb_lim.setObjectName("cb_lim")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_lim)
        self.cb_det = QtWidgets.QCheckBox(self.tab_2)
        self.cb_det.setObjectName("cb_det")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_det)
        self.verticalLayout_3.addLayout(self.verticalLayoutCheckBoxes)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayoutOptions.addWidget(self.tabWidget)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutOptions.addItem(spacerItem5)
        self.verticalLayoutThreshould = QtWidgets.QVBoxLayout()
        self.verticalLayoutThreshould.setObjectName("verticalLayoutThreshould")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayoutThreshould.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.checkBox_3 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_5.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_5.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_5.addWidget(self.checkBox_5)
        self.verticalLayoutThreshould.addLayout(self.verticalLayout_5)
        self.btn_start = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_start.setMaximumSize(QtCore.QSize(12312333, 16777215))
        self.btn_start.setObjectName("btn_start")
        self.verticalLayoutThreshould.addWidget(self.btn_start)
        self.verticalLayoutOptions.addLayout(self.verticalLayoutThreshould)
        self.horizontalLayout_2.addLayout(self.verticalLayoutOptions)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(58, 433, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.actionSimples = QtWidgets.QAction(MainWindow)
        self.actionSimples.setObjectName("actionSimples")
        self.actionIn_Plotter = QtWidgets.QAction(MainWindow)
        self.actionIn_Plotter.setObjectName("actionIn_Plotter")
        self.actionThread = QtWidgets.QAction(MainWindow)
        self.actionThread.setObjectName("actionThread")
        self.actionDesativado = QtWidgets.QAction(MainWindow)
        self.actionDesativado.setObjectName("actionDesativado")
        self.actionProcessamento = QtWidgets.QAction(MainWindow)
        self.actionProcessamento.setCheckable(False)
        self.actionProcessamento.setObjectName("actionProcessamento")
        self.menuConfiguracoes.addAction(self.actionProcessamento)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuConfiguracoes.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EEG App - Instrumentação Biomédica 1"))
        self.label_replace.setText(_translate("MainWindow", "Chart Here"))
        self.lbl_status.setText(_translate("MainWindow", "Status:"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuConfiguracoes.setTitle(_translate("MainWindow", "Configurações"))
        self.label_8.setText(_translate("MainWindow", "Window Size: 100ms"))
        self.label_6.setText(_translate("MainWindow", "High-pass: 0.1 Hz"))
        self.label_7.setText(_translate("MainWindow", "Low-pass: 20 Hz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Opções"))
        self.btn_calib.setToolTip(_translate("MainWindow", "Calibrar"))
        self.btn_calib.setText(_translate("MainWindow", "Procurar"))
        self.cb_emg.setText(_translate("MainWindow", "Show Trigger"))
        self.cb_hbt.setText(_translate("MainWindow", "Op 2"))
        self.cb_ret.setText(_translate("MainWindow", "Op 3"))
        self.cb_env.setText(_translate("MainWindow", "--"))
        self.cb_lim.setText(_translate("MainWindow", "--"))
        self.cb_det.setText(_translate("MainWindow", "--"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "+"))
        self.label_10.setText(_translate("MainWindow", "Canais"))
        self.checkBox.setText(_translate("MainWindow", "CH1"))
        self.checkBox_2.setText(_translate("MainWindow", "CH2"))
        self.label_9.setText(_translate("MainWindow", "Processamento"))
        self.checkBox_3.setText(_translate("MainWindow", "Promediação"))
        self.checkBox_4.setText(_translate("MainWindow", "MNP"))
        self.checkBox_5.setText(_translate("MainWindow", "P300"))
        self.btn_start.setToolTip(_translate("MainWindow", "Start"))
        self.btn_start.setText(_translate("MainWindow", "Start/Stop"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.label_4.setText(_translate("MainWindow", "SIM"))
        self.actionSimples.setText(_translate("MainWindow", "Processamento"))
        self.actionIn_Plotter.setText(_translate("MainWindow", "In Plotter"))
        self.actionThread.setText(_translate("MainWindow", "Thread"))
        self.actionDesativado.setText(_translate("MainWindow", "Desativado"))
        self.actionProcessamento.setText(_translate("MainWindow", "A implementar"))

